# Generated by Django 2.0.2 on 2018-03-26 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('V', 'visible'), ('I', 'invisible')], default='male', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Image')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Inventory')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('lname', models.CharField(blank=True, default='', max_length=100)),
                ('id_number', models.CharField(blank=True, default='', max_length=13)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='male', max_length=100)),
                ('birthdate', models.CharField(blank=True, default='', max_length=10)),
                ('facebook', models.CharField(blank=True, default='', max_length=100)),
                ('lineid', models.CharField(blank=True, default='', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openDate', models.DateTimeField(auto_now_add=True)),
                ('executeDate', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradings', to='trader.Trader')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='trader.Trader')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Tag')),
            ],
            options={
                'ordering': ('openDate',),
            },
        ),
        migrations.AddField(
            model_name='review',
            name='trade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trading'),
        ),
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trader'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Tag'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trader'),
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Item'),
        ),
        migrations.AddField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trader'),
        ),
        migrations.AddField(
            model_name='basket',
            name='trade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trading'),
        ),
    ]
