# Generated by Django 2.0.2 on 2018-03-31 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20180330_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Image')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ItemOfBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ItemOfInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ItemTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TradingTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Tag')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('deleted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='trader.User')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted', to='trader.User')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.RemoveField(
            model_name='item',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trade_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='trading',
            name='tags',
        ),
        migrations.AddField(
            model_name='tradingtags',
            name='trading_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trading'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Review'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='trade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Trading'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.User'),
        ),
        migrations.AddField(
            model_name='itemtags',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Item'),
        ),
        migrations.AddField(
            model_name='itemtags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Tag'),
        ),
        migrations.AddField(
            model_name='itemofinventory',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Inventory'),
        ),
        migrations.AddField(
            model_name='itemofinventory',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Item'),
        ),
        migrations.AddField(
            model_name='itemofbasket',
            name='basket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Basket'),
        ),
        migrations.AddField(
            model_name='itemofbasket',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Item'),
        ),
        migrations.AddField(
            model_name='imageofitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Item'),
        ),
    ]
