# Generated by Django 2.0.2 on 2018-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_auto_20180404_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('V', 'visible'), ('I', 'invisible')], default='V', max_length=100),
        ),
        migrations.AlterField(
            model_name='trader',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=100),
        ),
    ]
