# Generated by Django 2.0.2 on 2018-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_auto_20180416_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
