# Generated by Django 2.0.2 on 2018-04-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.Image'),
        ),
    ]
