# Generated by Django 2.0.2 on 2018-04-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_auto_20180428_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='imageofitem',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='itemtags',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tradingtags',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
