# Generated by Django 2.0.2 on 2018-04-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_auto_20180428_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='updated',
        ),
        migrations.AddField(
            model_name='basket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
